/**
 * The landing page. AppSpec section 2.
 *
 * Four rows, one per level, smallest first, each with New and Load. The
 * application opens here because there are four things a user might have come
 * to do and no way to guess which, and it comes back here when one of them is
 * finished with.
 *
 * Nothing is generated by the landing page itself. It is a chooser, and a user
 * who opens it and closes it again has rolled nothing. AppSpec 2.5.
 *
 * Only the planet row is wired. The other three levels are specified and not
 * built, and index.html says why they are on screen anyway.
 */

/** Which of the levels the window is showing. One attribute, read by the CSS. */
export type AppView = "landing" | "planet" | "system" | "subsector";

export function setAppView(view: AppView): void {
  document.body.dataset.view = view;
}

export function currentAppView(): AppView {
  const view = document.body.dataset.view;
  return view === "planet" || view === "system" || view === "subsector" ? view : "landing";
}

/**
 * What the landing page has to say, in its own status line rather than the
 * planet panel's. A load that fails on the way in has to report where the user
 * is standing, which is here.
 */
export function landingSay(message: string, isError = false): void {
  const status = document.getElementById("landing-status");
  if (!status) return;
  status.textContent = message;
  status.classList.toggle("error", isError);
}

export interface LandingHandlers {
  /** Roll a new planet and open it. AppSpec 3.1. */
  planetNew(): void;
  /** Pick a planet file and open it. AppSpec 3.2. */
  planetLoad(): void | Promise<void>;
  /** Roll a new system and open it. AppSpec 3.1, SystemSpec section 8. */
  systemNew(): void;
  /** Pick the folder a system lives in and open it. AppSpec 3.3. */
  systemLoad(): void | Promise<void>;
  /** Roll a new subsector and open its chart. SubSectorSpec section 4. */
  subsectorNew(): void;
}

export function wireLanding(handlers: LandingHandlers): void {
  const click = (id: string, run: () => void | Promise<void>) => {
    const button = document.getElementById(id);
    if (!button) throw new Error(`Missing element #${id}`);
    button.addEventListener("click", () => {
      landingSay("");
      void run();
    });
  };
  click("landing-planet-new", handlers.planetNew);
  click("landing-planet-load", handlers.planetLoad);
  click("landing-system-new", handlers.systemNew);
  click("landing-system-load", handlers.systemLoad);
  click("landing-sub-new", handlers.subsectorNew);
}
